import Link from 'next/link';
import {notFound} from 'next/navigation';
import {C,D,PHONE,langs,slugs} from '../../../../lib/content';

export function generateStaticParams(){return langs.flatMap(lang=>slugs[lang].map(slug=>({lang,slug})))}
const serviceIndex=(lang,slug)=>slugs[lang]?.indexOf(slug) ?? -1;
const altPath=(lang,slug,target)=>{const i=serviceIndex(lang,slug);return i<0?`/${target}`:`/${target}/services/${slugs[target][i]}`};
export async function generateMetadata({params}){const {lang,slug}=await params;const d=D[lang]?.[slug];if(!d)return {};return {title:`${d[0]} | REHAB.AM`,description:d[1],alternates:{canonical:`/${lang}/services/${slug}`,languages:{hy:altPath(lang,slug,'hy'),ru:altPath(lang,slug,'ru'),en:altPath(lang,slug,'en'),'x-default':altPath(lang,slug,'hy')}},openGraph:{title:`${d[0]} | REHAB.AM`,description:d[1],type:'website',images:['/images/center-1.jpg']}}}

export default async function Service({params}){const {lang,slug}=await params;const t=C[lang],d=D[lang]?.[slug];if(!t||!d)notFound();const i=serviceIndex(lang,slug);const faq=t.qs.slice(0,3);const schema={"@context":"https://schema.org","@type":"MedicalWebPage",name:d[0],description:d[1],inLanguage:lang,about:{"@type":"Thing",name:d[0]},publisher:{"@type":"Organization",name:'REHAB.AM',url:'https://rehab.am',telephone:PHONE}};return <main><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema)}}/><header><Link href={`/${lang}`}><img src="/images/logo.png" alt="REHAB.AM"/></Link><Link href={`/${lang}`}>← {t.home}</Link><div className="langs">{langs.map(x=><Link className={lang===x?'on':''} href={i<0?`/${x}`:`/${x}/services/${slugs[x][i]}`} key={x}>{x.toUpperCase()}</Link>)}</div></header><section className="serviceHero"><div><b>REHAB.AM</b><h1>{d[0]}</h1><p>{d[1]}</p><a className="cta" href={`tel:${PHONE}`}>{t.call}</a></div><img src={`/images/center-${(i%5)+1}.jpg`} alt={d[0]}/></section><section className="serviceBody"><article><h2>{d[2][0]}</h2><p>{d[2][1]}</p></article><article><h2>{d[3][0]}</h2><p>{d[3][1]}</p></article><article><h2>{t.journey}</h2><p>{t.journeySub}. {t.lifeText}</p></article></section><section className="dark"><b>{t.journey}</b><h2>{t.journeySub}</h2><div className="steps">{t.steps.map((x,n)=><div key={x}><span>{String(n+1).padStart(2,'0')}</span>{x}</div>)}</div></section><section className="why"><b>{t.why}</b><h2>{t.whyTitle}</h2><div>{t.points.map(x=><span key={x}>✓ {x}</span>)}</div></section><section className="section"><b>{t.faqTitle}</b><div className="faq">{faq.map(q=><details key={q[0]}><summary>{q[0]}</summary><p>{q[1]}</p></details>)}</div></section><section className="end"><img src="/images/logo.png" alt="REHAB.AM"/><h2>{t.end}</h2><a className="cta light" href={`tel:${PHONE}`}>{t.call}</a><a className="phone" href={`tel:${PHONE}`}>+374 99 620 620</a><p>{t.private}</p><Link className="back" href={`/${lang}`}>← {t.home}</Link></section></main>}
